CREATE TABLE tabs(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tabName TEXT NOT NULL
);

INSERT INTO tabs(tabName)
values
    ('PCs'),
    ('NPCs'),
    ('locations'),
    ('organizations'),
    ('world stories/history'),
    ('plot story');